### ISSUE TITLE
issue-073 detail page 관련된 dao , detailMapper, service method 이름/순서 정리

### ISSUE THREAD

**Issue by yeongjae-yu** [EinHugo/SINC-WebProjectCodeVisualizatior#139]
### 개요
- detail page와 관련된 모든 메소드들 이름 및 기능 순대로 순서 정리

 <hr>

 ### 체크리스트
- DetailService
- DetailDao
- detailMapper

**Comment by EinHugo** [comment]
DAO에서 Mapper 파일의 Query 호출하는 부분 네임스페이스 맞춰주세요 ^~^

**Comment by yeongjae-yu** [comment]
complete
