### ISSUE TITLE
issue-181 한글이 깨져 출력되는 이슈

### ISSUE THREAD

**Issue by EinHugo** [EinHugo/SINC-WebProjectCodeVisualizatior#328]
### 개요
- DB에 저장되어있는 한글이 깨져 보이는 이슈
![image](https://user-images.githubusercontent.com/23213433/64257915-36391a00-cf61-11e9-83d2-d474fecb8a44.png)

 <hr>

 ### 체크리스트
- DB 캐릭터셋 셋팅 확인
- 클라이언트 툴 셋팅 확인
- 전송시 엔디안 확인

**Comment by EinHugo** [comment]
파싱 모듈의 문제인 것으로 추측

![image](https://user-images.githubusercontent.com/23213433/64284606-f0964480-cf94-11e9-8bbc-3467406d9d23.png)

**Comment by labyrenth** [comment]
![image](https://user-images.githubusercontent.com/24791050/64303912-44208680-cfc5-11e9-9989-04278c1573be.png)
직접 XML에 한글로 집어넣은 자료도 오류가 나는 것으로 보아, DB의 charset 문제인것으로 추측됨.

**Comment by labyrenth** [comment]
![image](https://user-images.githubusercontent.com/24791050/64304599-716e3400-cfc7-11e9-9035-0aae524aa2d6.png)
mariaDB 설정 수정해서 한글문제 해결한 듯 싶음. 자료는 추후에 다시 추가할것.
