### ISSUE TITLE
issue-182 그래프가 서비스 이후 DAO로 연결되지 않는 이슈

### ISSUE THREAD

**Issue by EinHugo** [EinHugo/SINC-WebProjectCodeVisualizatior#329]
### 개요
-그래프가 서비스까지만 출력되고 끊기는 이슈

![image](https://user-images.githubusercontent.com/23213433/64258103-90d27600-cf61-11e9-90c4-75109229fc47.png)

 <hr>

 ### 체크리스트
- 메소드 릴레이션 확인

**Comment by labyrenth** [comment]
interface를 코드에서 전부 제거함으로써 일단 해결
